config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root :to => 'home#index'
  resources :reservations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservations.rb
class Reservations < ActiveRecord::Base

  TICKET_LIMIT = 40

  validates :email, :name, :tickets, presence: true
  validates :email, uniqueness: true
  validate :tickets_cant_exceed_limit

  def tickets_cant_exceed_limit
    if (Reservations.sum(:tickets) + self.tickets) > TICKET_LIMIT
      errors.add(:tickets, "can't exceed limit")
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    tickets_sum = Reservations.sum(:tickets)
    @reservation = Reservations.new
    @is_submitted = params[:submitted] == "true"
    @has_errors = params[:errors] == "true"
    @is_full = tickets_sum >= Reservations::TICKET_LIMIT
    @tickets_available = [8, (Reservations::TICKET_LIMIT - tickets_sum)].min
  end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  def index
    @reservations = Reservations.all
    @sum = Reservations.sum(:tickets)
  end

  def create
    @reservation = Reservations.new(reservation_params)
    if @reservation.save
      redirect_to root_path(submitted: true)
    else
      @tickets_available = [8, (Reservations::TICKET_LIMIT - Reservations.sum(:tickets))].min
      redirect_to root_path(errors: true, anchor: "form")
    end
  end

  def destroy
    Reservations.find(params[:id]).destroy
    redirect_to reservations_path
  end

  private

    def reservation_params
      params.require(:reservations).permit(:email, :name, :tickets)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<img src="https://media.entertainmentearth.com/assets/images/3872513dc4c24460a3d19eb78a0606d5.jpg" width="100%">
<div class="container mb-5 pb-5">
  <section class="box single-column-width mx-auto position-relative" style="margin-top: -2.25rem;">
    <div class="text-center">
      <img src="https://www.embraceoregon.org/images/embrace-oregon.svg" height="96">
      <h1>RSVP for Toy Story 4</h1>
    </div>

    <% if @is_submitted %>
      <p class="mt-4">Thank you for your request for tickets! If you are seeing this screen, your request has been accepted.</p>
      <p>You may hear from the film company during the week of June 10th with any additional details.</p>
      <p>Please remember that you are only guaranteed your seats if you arrive prior to 6:40 PM. After that time, the seats will be opened to the general public.</p>
      <p>To be safe, arrive to the theater <strong>prior to 6:30PM</strong> and check in at the lobby with the film's on site representative. You will check in using the name with which you RSVP'd.</p>
      <p><strong>Showtime: Tuesday, June 18 @ Regal Tigard 11-  7PM.</strong></p>
      <p>Thank you & enjoy!<br>&dash; Embrace Oregon Team</p>

    <% elsif @is_full %>
      <p class="mt-4">Unfortunately, we have reached our capacity for this film screening. We hope to offer more in the future.</p>
      <p>Your role as a foster family in our community is seen and valued!</p>

    <% else %>
      <h5 class="text-muted mb-4 font-weight-normal">This summer, Embrace Oregon is thrilled to partner with Allied Global Marketing to offer <strong>40 free tickets</strong> to a prescreening of Toy Story 4!</h5>
      <h6>Details</h6>
      <ul>
        <li>Tuesday, June 18 @ Regal Tigard 11. Showtime at 7PM.</li>
        <li>You must RSVP below AND arrive by 6:30PM to claim your seats.</li>
        <li>Theater Address: 11626 SW Pacific HWY, Tigard, OR 97223</li>
      </ul>
      <p>RSVP'd guests have guaranteed admittance prior to 6:40PM. After that time seating is on a first-come first-serve basis, and your seat is not guaranteed.</p>
      <p>When you arrive, please check in at the lobby with the film's on site representative & the EO team and claim your seat using the name you RSVP'd with.</p>
      <p>You will not need any kind of physical passes to attend and you will be admitted free of charge.</p>
      <p>We are so thankful for your commitment to children in care and wanted to simply say "thank you" for all that you do! <strong>We are better because of YOU!</strong></p>
      <iframe width="544" height="306" src="https://www.youtube.com/embed/wmiIUN-7qhE" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen class="mt-4"></iframe>
      <hr id="form" class="my-5">
      <%= form_for @reservation, url: { controller: "reservations", action: "create" } do |f| %>
        <% if @has_errors %>
          <div class="alert alert-danger mb-4">
            We were unable to submit your RSVP either because you've all ready signed up with that email address, or we are approaching our ticket limit. Feel free to try again.
          </div>
        <% end %>
        <h3>Reserve Your Tickets</h3>
        <div class="form-group mt-4">
          <label for="reservations_email">Your Email Address</label>
          <%= f.email_field :email, class: "form-control", placeholder: "example@email.com", required: true %>
        </div>
        <div class="form-group">
          <label for="reservations_name">Your Full Name</label>
          <%= f.text_field :name, class: "form-control", required: true %>
        </div>
        <div class="form-group">
          <label>How many tickets would you like?</label>
          <% (1..@tickets_available).each do |i| %>
            <label class="form-check pl-0">
              <%= f.radio_button :tickets, i, required: true %>
              <span class="ml-2"><%= i %></span>
            </label>
          <% end %>
        </div>
        <%= f.submit "Reserve", class: "btn btn-primary px-4 mt-4"%>
      <% end %>
    <% end %>
  </section>
</div>

<script>
  (function () {
    if (location.search.indexOf('errors') >= 0) {
      history.replaceState({}, "don't double errors", "/#form")
    }
  }());
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Embrace Oregon Toy Story 4 Rsvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="robots" content="noindex, nofollow">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/reservations/index.html.erb
<section class="container my-5">
  <h1>Toy Story 4 RSVPs</h1>
  <table class="table mt-4">
    <thead>
      <tr>
        <th>Email Address</th>
        <th>Name</th>
        <th>Tickets Requested</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @reservations.each do |res| %>
        <tr>
          <td><%= res.email %></td>
          <td><%= res.name %></td>
          <td><%= res.tickets %></td>
          <td><%= link_to "Delete", reservation_path(res), method: :delete, class: "text-danger small", confirm: "Are you sure?" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="mt-5">
    Ticket Total: <strong><%= @sum %></strong>
  </div>
</section>